// src/components/Header.jsx
import { Fragment } from 'react'
import Link from 'next/link'
import { Popover, Transition } from '@headlessui/react'
import clsx from 'clsx'

import { Button } from '@/components/Button'
import { Container } from '@/components/Container'
import { Logo } from '@/components/Logo'
import { NavLink } from '@/components/NavLink'

function MobileNavLink({ href, children }) {
  return (
    <Popover.Button as={Link} href={href} className="block w-full p-2">
      {children}
    </Popover.Button>
  )
}

function MobileNavIcon({ open }) {
  return (
    <svg
      aria-hidden="true"
      className="h-3.5 w-3.5 overflow-visible stroke-slate-700"
      fill="none"
      strokeWidth={2}
      strokeLinecap="round"
    >
      <path
        d="M0 1H14M0 7H14M0 13H14"
        className={clsx(
          'origin-center transition',
          open && 'scale-90 opacity-0'
        )}
      />
      <path
        d="M2 2L12 12M12 2L2 12"
        className={clsx(
          'origin-center transition',
          !open && 'scale-90 opacity-0'
        )}
      />
    </svg>
  )
}

function MobileNavigation() {
  return (
    <Popover>
      <Popover.Button
        className="relative z-10 flex h-8 w-8 items-center justify-center [&:not(:focus-visible)]:focus:outline-none"
        aria-label="Toggle Navigation"
      >
        {({ open }) => <MobileNavIcon open={open} />}
      </Popover.Button>
      <Transition.Root>
        <Transition.Child
          as={Fragment}
          enter="duration-150 ease-out"
          enterFrom="opacity-0"
          enterTo="opacity-100"
          leave="duration-150 ease-in"
          leaveFrom="opacity-100"
          leaveTo="opacity-0"
        >
          <Popover.Overlay className="fixed inset-0 bg-slate-300/50" />
        </Transition.Child>
        <Transition.Child
          as={Fragment}
          enter="duration-150 ease-out"
          enterFrom="opacity-0 scale-95"
          enterTo="opacity-100 scale-100"
          leave="duration-100 ease-in"
          leaveFrom="opacity-100 scale-100"
          leaveTo="opacity-0 scale-95"
        >
          <Popover.Panel
            as="div"
            className="absolute inset-x-0 top-full mt-4 flex origin-top flex-col rounded-2xl bg-white p-4 text-lg tracking-tight text-slate-900 shadow-xl ring-1 ring-slate-900/5"
          >
            <MobileNavLink href="/creators">Creators</MobileNavLink>
            <MobileNavLink href="/businesses">Businesses</MobileNavLink>
            <MobileNavLink href="/about">About</MobileNavLink>
          </Popover.Panel>
        </Transition.Child>
      </Transition.Root>
    </Popover>
  )
}

export function Header() {
  return (
    <header className="py-6 lg:py-10">
      <Container>
        <nav className="relative z-50 flex justify-between">
          <div className="flex items-center md:gap-x-12">
            <Link href="/" aria-label="Home">
              <Logo className="h-8 w-auto fill-slate-900" />
            </Link>
            <div className="hidden md:flex md:gap-x-6">
              <NavLink href="/creators">Creators</NavLink>
              <NavLink href="/businesses">Businesses</NavLink>
              <NavLink href="/about">About</NavLink>
            </div>
          </div>
          <div className="flex items-center gap-x-5 md:gap-x-8">
            <Button href="/contact" color="slate">
              <span>
                Get started <span className="hidden lg:inline">today</span>
              </span>
            </Button>
            <div className="-mr-1 md:hidden">
              <MobileNavigation />
            </div>
          </div>
        </nav>
      </Container>
    </header>
  )
}

// components/Header.vue
<template>
  <Popover
    class="fixed top-0 left-0 z-40 w-full p-2 transition-all duration-500 ease-in-out ui-not-open:mix-blend-difference ui-not-open:invert sm:p-4">
    <div class="relative z-10 mx-auto flex w-full max-w-8xl items-center justify-between border border-neutral-900">
      <div class="shrink-0 pl-4">
        <NuxtLink @click="close" to="/">
          <DopeLogo class="text-5xl ui-open:text-neutral-300" />
        </NuxtLink>
      </div>

      <div class="w-24 shrink-0 xl:w-40">
        <PopoverButton
          class="inline-flex h-12 w-full items-center justify-center bg-neutral-900 text-center font-bold uppercase text-neutral-200">
          <span class="sr-only">Toggle menu</span>
          Menu
        </PopoverButton>
      </div>
    </div>

    <transition
      enter-active-class="duration-500 ease-out"
      enter-from-class="-translate-y-full"
      enter-to-class="translate-y-0"
      leave-active-class="duration-500 ease-in"
      leave-from-class="translate-y-0"
      leave-to-class="-translate-y-full">
      <PopoverPanel
        v-slot="{ close }"
        focus
        class="absolute inset-x-0 top-0 z-0 min-h-screen w-full origin-top transform bg-neutral-900 transition">
        <DopeContainer>
          <nav class="mt-64 text-5xl text-neutral-300 xl:text-7xl">
            <NuxtLink @click="close" to="/projects" class="block py-2">Work</NuxtLink>
            <NuxtLink @click="close" to="/coming-soon" class="block py-2">Ideas</NuxtLink>
            <NuxtLink @click="close" to="/about" class="block py-2">About</NuxtLink>
            <NuxtLink @click="close" to="/contact" class="block py-2">Get in touch</NuxtLink>
          </nav>
        </DopeContainer>
      </PopoverPanel>
    </transition>
  </Popover>
</template>

<script setup>
import { Popover, PopoverButton, PopoverGroup, PopoverPanel } from '@headlessui/vue'
</script>
