// src/pages/contact.jsx
import { Button } from '@/components/Button'
import { Container } from '@/components/Container'
import { Dots } from '@/components/Dots'
import Head from 'next/head'

export default function Contact() {
  return (
    <>
      <Head>
        <title>
          Schedule a call or email us to get started | Really Dope Digital
        </title>
        <meta
          name="description"
          content="Schedule a call or email us to get started"
        />
      </Head>
      <main>
        <Container className="pt-12 pb-16 lg:pt-32 lg:pb-32">
          <div>
            <h2 className="text-sm font-bold uppercase text-emerald-400">
              Contact Us
            </h2>
            <p className="my-6 max-w-lg text-3xl font-bold leading-normal tracking-tight text-white lg:text-4xl">
              Schedule a phone call or email us to get started
            </p>
            <p className="my-6 max-w-2xl text-lg text-zinc-200">
              Whether you're ready to get moving on a project right away or just
              want some more info, we're here to talk. Schedule a call online or
              email us at <strong>hey@thatsrdd.com</strong>.
            </p>

            <div class="mt-8">
              <Button
                href="https://calendly.com/samrapaport"
                target="_blank"
                size="large"
              >
                Book Phone Call
              </Button>
            </div>
          </div>
        </Container>
      </main>
    </>
  )
}

// pages/contact.vue
<template>
  <div>
    <Head>
      <Title>Contact</Title>
    </Head>

    <DopeHero title="Create with us &#10036;&#xFE0E;&nbsp;"> Are you ready to build something Dope? </DopeHero>

    <DopeSection>
      <DopeContainer>
        <p class="mb-8 max-w-5xl text-lg font-bold">
          We're here for it. Schedule a call with our team or email us at
          <span class="underline">hey@thatsrdd.com</span>.
        </p>
        <DopeButton to="https://calendly.com/samrapaport" target="_blank">Schedule a Call</DopeButton>
      </DopeContainer>
    </DopeSection>
  </div>
</template>
